name: Reclutamiento de Agente

on: push

jobs:
  repote-de-reclutamientoo:
   run-on: ubuntu-latest

  steps:
    - name:  El agente se presenta.
    - run: echo "Soy Lex Luthor, y el liderr de la Legion del Mal"