name: Acceso a la Fortaleza Prohibida

on:
  push:

jobs:
  acceso-a-la-base:
    runs-on: ubuntu-latest

    steps:
      - name: Brainiac desbloquea la bóveda
        uses: actions/checkout@v4

      - name: Ahora sí, vamos a ver los planes
        run: |
          echo "Buscando los archivos de la legión..."
          ls -la
          echo "✅ Planes encontrados."
          echo ""
          echo "Planes:"
          ls planes/
          echo "Villanos:"
          ls miembros/
          echo "Inteligencia:"
          ls inteligencia/
